#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define NOTOSANS_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_14_regular.h",
  "./notosans_14_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_16_regular.h",
  "./notosans_16_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_derivative_paperpoint_10_regular.h",
  "./ubuntu_derivative_paperpoint_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_derivative_paperpoint_12_regular.h",
  "./ubuntu_derivative_paperpoint_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
