#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define NOTOSANS_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_12_regular.h",
  "./notosans_12_bold.h",
  "./notosans_12_bolditalic.h",
  "./notosans_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_14_regular.h",
  "./notosans_14_bold.h",
  "./notosans_14_bolditalic.h",
  "./notosans_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_16_regular.h",
  "./notosans_16_bold.h",
  "./notosans_16_bolditalic.h",
  "./notosans_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_18_regular.h",
  "./notosans_18_bold.h",
  "./notosans_18_bolditalic.h",
  "./notosans_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define READERDYSLEXIC_8_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./readerdyslexic_8_regular.h",
  "./readerdyslexic_8_bold.h",
  "./readerdyslexic_8_bolditalic.h",
  "./readerdyslexic_8_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define READERDYSLEXIC_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./readerdyslexic_10_regular.h",
  "./readerdyslexic_10_bold.h",
  "./readerdyslexic_10_bolditalic.h",
  "./readerdyslexic_10_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define READERDYSLEXIC_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./readerdyslexic_12_regular.h",
  "./readerdyslexic_12_bold.h",
  "./readerdyslexic_12_bolditalic.h",
  "./readerdyslexic_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define READERDYSLEXIC_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./readerdyslexic_14_regular.h",
  "./readerdyslexic_14_bold.h",
  "./readerdyslexic_14_bolditalic.h",
  "./readerdyslexic_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_derivative_paperpoint_10_regular.h",
  "./ubuntu_derivative_paperpoint_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_derivative_paperpoint_12_regular.h",
  "./ubuntu_derivative_paperpoint_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
