#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

write_font() {
  local output_path="$1"
  local notice="$2"
  shift 2
  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' RETURN
  python fontconvert.py "$@" > "$tmp"
  {
    printf '%s\n' "$notice"
    cat "$tmp"
  } > "$output_path"
  rm -f "$tmp"
  trap - RETURN
  echo "Generated $output_path"
}

NOTO_NOTICE='/*
 * SPDX-License-Identifier: OFL-1.1
 * Noto Sans bitmap font data generated by format conversion.
 * Copyright 2022 The Noto Project Authors.
 * Full licence: LICENSES/OFL-1.1-NotoSans.txt.
 */'

READER_DYSLEXIC_NOTICE='/*
 * SPDX-License-Identifier: OFL-1.1
 * Reader Dyslexic bitmap derivative generated from unmodified OpenDyslexic
 * font software. Original font copyright (c) 2019 Abbie Gonzalez and
 * contributors. Original Reserved Font Name: OpenDyslexic.
 * This generated derivative uses the different name Reader Dyslexic.
 * Full licence: LICENSES/OFL-1.1-OpenDyslexic.txt.
 */'

UBUNTU_NOTICE='/*
 * SPDX-License-Identifier: Ubuntu-font-1.0
 * Ubuntu derivative PaperPoint bitmap font generated by format conversion
 * from Ubuntu Font Family source files. Copyright 2011 Canonical Ltd.
 * The modified output is renamed in
 * accordance with the Ubuntu Font Licence 1.0.
 * Full licence: LICENSES/UFL-1.0.txt.
 */'

READER_FONT_STYLES=(Regular Italic Bold BoldItalic)
NOTOSANS_FONT_SIZES=(12 14 16 18)
READERDYSLEXIC_FONT_SIZES=(8 10 12 14)

for size in "${NOTOSANS_FONT_SIZES[@]}"; do
  for style in "${READER_FONT_STYLES[@]}"; do
    style_lower="$(echo "$style" | tr '[:upper:]' '[:lower:]')"
    font_name="notosans_${size}_${style_lower}"
    font_path="../builtinFonts/source/NotoSans/NotoSans-${style}.ttf"
    output_path="../builtinFonts/${font_name}.h"
    write_font "$output_path" "$NOTO_NOTICE" \
      "$font_name" "$size" "$font_path" --2bit --compress
  done
done

for size in "${READERDYSLEXIC_FONT_SIZES[@]}"; do
  for style in "${READER_FONT_STYLES[@]}"; do
    style_lower="$(echo "$style" | tr '[:upper:]' '[:lower:]')"
    font_name="readerdyslexic_${size}_${style_lower}"
    font_path="../builtinFonts/source/OpenDyslexic/OpenDyslexic-${style}.otf"
    output_path="../builtinFonts/${font_name}.h"
    write_font "$output_path" "$READER_DYSLEXIC_NOTICE" \
      "$font_name" "$size" "$font_path" --2bit --compress
  done
done

UI_FONT_SIZES=(10 12)
UI_FONT_STYLES=(Regular Bold)
for size in "${UI_FONT_SIZES[@]}"; do
  for style in "${UI_FONT_STYLES[@]}"; do
    style_lower="$(echo "$style" | tr '[:upper:]' '[:lower:]')"
    font_name="ubuntu_derivative_paperpoint_${size}_${style_lower}"
    font_path="../builtinFonts/source/Ubuntu/Ubuntu-${style}.ttf"
    output_path="../builtinFonts/${font_name}.h"
    write_font "$output_path" "$UBUNTU_NOTICE" \
      "$font_name" "$size" "$font_path"
  done
done

write_font ../builtinFonts/notosans_8_regular.h "$NOTO_NOTICE" \
  notosans_8_regular 8 ../builtinFonts/source/NotoSans/NotoSans-Regular.ttf

echo
echo "Running compression verification..."
python verify_compression.py ../builtinFonts/
