#pragma once

#include <builtinFonts/paperpoint_sans_tc_15_5_medium.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/readerdyslexic_10_bold.h>
#include <builtinFonts/readerdyslexic_10_bolditalic.h>
#include <builtinFonts/readerdyslexic_10_italic.h>
#include <builtinFonts/readerdyslexic_10_regular.h>
#include <builtinFonts/readerdyslexic_12_bold.h>
#include <builtinFonts/readerdyslexic_12_bolditalic.h>
#include <builtinFonts/readerdyslexic_12_italic.h>
#include <builtinFonts/readerdyslexic_12_regular.h>
#include <builtinFonts/readerdyslexic_14_bold.h>
#include <builtinFonts/readerdyslexic_14_bolditalic.h>
#include <builtinFonts/readerdyslexic_14_italic.h>
#include <builtinFonts/readerdyslexic_14_regular.h>
#include <builtinFonts/readerdyslexic_8_bold.h>
#include <builtinFonts/readerdyslexic_8_bolditalic.h>
#include <builtinFonts/readerdyslexic_8_italic.h>
#include <builtinFonts/readerdyslexic_8_regular.h>
#include <builtinFonts/ubuntu_derivative_paperpoint_10_bold.h>
#include <builtinFonts/ubuntu_derivative_paperpoint_10_regular.h>
#include <builtinFonts/ubuntu_derivative_paperpoint_12_bold.h>
#include <builtinFonts/ubuntu_derivative_paperpoint_12_regular.h>
