// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSANS_14_FONT_ID (1644846072)
#define NOTOSANS_16_FONT_ID (277691087)
#define UI_10_FONT_ID (273497352)
#define UI_12_FONT_ID (-1419242931)
#define SMALL_FONT_ID (-1557484977)
