name: Compile Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-compliance:
    uses: ./.github/workflows/release-compliance.yml
    permissions:
      contents: write